<?php

namespace App\Enum;

enum ErrorCode: string
{
    case USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';

    case ADDRESS_LIMIT_REACHED = 'ADDRESS_LIMIT_REACHED';
    case ADDRESS_ALREADY_EXISTS = 'ADDRESS_ALREADY_EXISTS';
    case ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND';
    case ADDRESS_CANNOT_DELETE_DEFAULT = 'ADDRESS_CANNOT_DELETE_DEFAULT';


    case INVALID_DATA = 'INVALID_DATA';
    case HTTP_INTERNAL_SERVER_ERROR = 'HTTP_INTERNAL_SERVER_ERROR';
}
